# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Rodar testes"
  lane :tests do
	run_tests(scheme: "MagLib",
	slack_url: "https://hooks.slack.com/services/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",
	slack_channel: "testefastlane")
    # add actions here: https://docs.fastlane.tools/actions
  end
end
