name: Swiftlint

on:
  pull_request:
    branches:
    - main
    - feature/*

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests
